version: "3"

# Try `docker-compose up`

services:
    ovpn_proxy:
        image: ghcr.io/nyamisty/corellium-proxy
        tty: true
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        dns:
            - 1.1.1.1
            - 1.0.0.1
        tmpfs:
            - /run
            - /run/lock
            - /tmp
        volumes:
            - ./config.ovpn:/etc/openvpn/client/corellium.conf
            - ./npsconf:/etc/nps/conf
            - /sys/fs/cgroup:/sys/fs/cgroup
        ports:
            - 15000:5000
            - 15010:8080
            - 15011:5080
            - "15100-15200:15100-15200"
        restart: always
